### ISSUE TITLE
Could not find com.kirich1409:strict-mode-compat:30.2.0

### ISSUE THREAD

**Issue by amatkivskiy** [kirich1409/StrictModeCompat#2]
Hi @kirich1409 

I've tried to use your library but got this : 
```
   > Could not find com.kirich1409:strict-mode-compat:30.2.0.
     Required by:
         project :app
   > Could not find com.kirich1409:strict-mode-compat-ktx:30.2.0.
     Required by:
         project :app
```

I've searched on the maven central and found library artifact there but it has different **group id**: 
in README:
`implementation "com.kirich1409:strict-mode-compat:30.2.0"`
on Maven Central: 
`implementation "com.github.kirich1409:strict-mode-compat:30.2.0"`

Same for Kotlin extensions library. 

Can you please fix this in README?

**Comment by kirich1409** [comment]
Hi. Thanks. I have done that
